import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata, Viewport } from "next";
import Script from "next/script";
import "./globals.css";


export const metadata: Metadata = {
  title: "ML",
  description: "Generated by your boy",
};

export const viewport: Viewport = {
  initialScale: 0.5
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>{children}</AntdRegistry>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"
          strategy="lazyOnload"></Script>
      </body>
    </html>
  );
}
